# Generated by Django 5.0.7 on 2024-07-20 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_tags_alter_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='it', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 21, 22, 53, 587574, tzinfo=datetime.timezone.utc)),
        ),
    ]
