# Generated by Django 5.0.7 on 2024-07-22 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_publish_alter_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_products_for_rest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 8, 40, 23, 794788, tzinfo=datetime.timezone.utc)),
        ),
    ]
